// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ServerPlace/iac-controller/internal/scm (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mock_client.go -package=scm github.com/ServerPlace/iac-controller/internal/scm Client
//

// Package scm is a generated GoMock package.
package scm

import (
	context "context"
	reflect "reflect"

	model "github.com/ServerPlace/iac-controller/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BranchStatus mocks base method.
func (m *MockClient) BranchStatus(ctx context.Context, owner, repo, sourceBranch, targetBranch string) (*GitBranchStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BranchStatus", ctx, owner, repo, sourceBranch, targetBranch)
	ret0, _ := ret[0].(*GitBranchStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BranchStatus indicates an expected call of BranchStatus.
func (mr *MockClientMockRecorder) BranchStatus(ctx, owner, repo, sourceBranch, targetBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BranchStatus", reflect.TypeOf((*MockClient)(nil).BranchStatus), ctx, owner, repo, sourceBranch, targetBranch)
}

// Comment mocks base method.
func (m *MockClient) Comment(ctx context.Context, owner, repo string, number int, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comment", ctx, owner, repo, number, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Comment indicates an expected call of Comment.
func (mr *MockClientMockRecorder) Comment(ctx, owner, repo, number, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comment", reflect.TypeOf((*MockClient)(nil).Comment), ctx, owner, repo, number, body)
}

// CommentUpdate mocks base method.
func (m *MockClient) CommentUpdate(ctx context.Context, owner, repo string, number int, key, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentUpdate", ctx, owner, repo, number, key, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommentUpdate indicates an expected call of CommentUpdate.
func (mr *MockClientMockRecorder) CommentUpdate(ctx, owner, repo, number, key, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentUpdate", reflect.TypeOf((*MockClient)(nil).CommentUpdate), ctx, owner, repo, number, key, body)
}

// FetchRepositoryMetadata mocks base method.
func (m *MockClient) FetchRepositoryMetadata(ctx context.Context, identifier string) (*model.RepositoryMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRepositoryMetadata", ctx, identifier)
	ret0, _ := ret[0].(*model.RepositoryMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRepositoryMetadata indicates an expected call of FetchRepositoryMetadata.
func (mr *MockClientMockRecorder) FetchRepositoryMetadata(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRepositoryMetadata", reflect.TypeOf((*MockClient)(nil).FetchRepositoryMetadata), ctx, identifier)
}

// GetPullRequest mocks base method.
func (m *MockClient) GetPullRequest(ctx context.Context, owner, repo string, number int) (*PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequest", ctx, owner, repo, number)
	ret0, _ := ret[0].(*PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequest indicates an expected call of GetPullRequest.
func (mr *MockClientMockRecorder) GetPullRequest(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequest", reflect.TypeOf((*MockClient)(nil).GetPullRequest), ctx, owner, repo, number)
}

// MergePR mocks base method.
func (m *MockClient) MergePR(ctx context.Context, owner, repo string, number int, headSHA string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, owner, repo, number, headSHA)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePR indicates an expected call of MergePR.
func (mr *MockClientMockRecorder) MergePR(ctx, owner, repo, number, headSHA any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockClient)(nil).MergePR), ctx, owner, repo, number, headSHA)
}

// SetStatus mocks base method.
func (m *MockClient) SetStatus(ctx context.Context, owner, repo, sha, state, description, targetURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, owner, repo, sha, state, description, targetURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockClientMockRecorder) SetStatus(ctx, owner, repo, sha, state, description, targetURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockClient)(nil).SetStatus), ctx, owner, repo, sha, state, description, targetURL)
}
