// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ServerPlace/iac-controller/internal/core/ports (interfaces: Persistence)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository.go -package=ports -mock_names Persistence=MockRepository github.com/ServerPlace/iac-controller/internal/core/ports Persistence
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	model "github.com/ServerPlace/iac-controller/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Persistence interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AcquireBatch mocks base method.
func (m *MockRepository) AcquireBatch(ctx context.Context, repo string, stacks []string, user string, prNum int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireBatch", ctx, repo, stacks, user, prNum)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcquireBatch indicates an expected call of AcquireBatch.
func (mr *MockRepositoryMockRecorder) AcquireBatch(ctx, repo, stacks, user, prNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireBatch", reflect.TypeOf((*MockRepository)(nil).AcquireBatch), ctx, repo, stacks, user, prNum)
}

// GetDeployment mocks base method.
func (m *MockRepository) GetDeployment(ctx context.Context, id string) (*model.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployment", ctx, id)
	ret0, _ := ret[0].(*model.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployment indicates an expected call of GetDeployment.
func (mr *MockRepositoryMockRecorder) GetDeployment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployment", reflect.TypeOf((*MockRepository)(nil).GetDeployment), ctx, id)
}

// GetDeploymentByPR mocks base method.
func (m *MockRepository) GetDeploymentByPR(ctx context.Context, repo string, prNumber int) (*model.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentByPR", ctx, repo, prNumber)
	ret0, _ := ret[0].(*model.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentByPR indicates an expected call of GetDeploymentByPR.
func (mr *MockRepositoryMockRecorder) GetDeploymentByPR(ctx, repo, prNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentByPR", reflect.TypeOf((*MockRepository)(nil).GetDeploymentByPR), ctx, repo, prNumber)
}

// GetJob mocks base method.
func (m *MockRepository) GetJob(ctx context.Context, jobID string) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockRepositoryMockRecorder) GetJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockRepository)(nil).GetJob), ctx, jobID)
}

// GetRepositoryByID mocks base method.
func (m *MockRepository) GetRepositoryByID(ctx context.Context, id string) (*model.RepositoryMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByID", ctx, id)
	ret0, _ := ret[0].(*model.RepositoryMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByID indicates an expected call of GetRepositoryByID.
func (mr *MockRepositoryMockRecorder) GetRepositoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByID", reflect.TypeOf((*MockRepository)(nil).GetRepositoryByID), ctx, id)
}

// GetRepositoryByName mocks base method.
func (m *MockRepository) GetRepositoryByName(ctx context.Context, name string) (*model.RepositoryMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByName", ctx, name)
	ret0, _ := ret[0].(*model.RepositoryMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByName indicates an expected call of GetRepositoryByName.
func (mr *MockRepositoryMockRecorder) GetRepositoryByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByName", reflect.TypeOf((*MockRepository)(nil).GetRepositoryByName), ctx, name)
}

// GetRepositoryByURI mocks base method.
func (m *MockRepository) GetRepositoryByURI(ctx context.Context, uri string) (*model.RepositoryMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByURI", ctx, uri)
	ret0, _ := ret[0].(*model.RepositoryMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByURI indicates an expected call of GetRepositoryByURI.
func (mr *MockRepositoryMockRecorder) GetRepositoryByURI(ctx, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByURI", reflect.TypeOf((*MockRepository)(nil).GetRepositoryByURI), ctx, uri)
}

// Release mocks base method.
func (m *MockRepository) Release(ctx context.Context, repo, stackPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, repo, stackPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockRepositoryMockRecorder) Release(ctx, repo, stackPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockRepository)(nil).Release), ctx, repo, stackPath)
}

// ReleaseBatch mocks base method.
func (m *MockRepository) ReleaseBatch(ctx context.Context, repo string, prNum int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseBatch", ctx, repo, prNum)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseBatch indicates an expected call of ReleaseBatch.
func (mr *MockRepositoryMockRecorder) ReleaseBatch(ctx, repo, prNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseBatch", reflect.TypeOf((*MockRepository)(nil).ReleaseBatch), ctx, repo, prNum)
}

// SaveDeployment mocks base method.
func (m *MockRepository) SaveDeployment(ctx context.Context, d *model.Deployment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDeployment", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDeployment indicates an expected call of SaveDeployment.
func (mr *MockRepositoryMockRecorder) SaveDeployment(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDeployment", reflect.TypeOf((*MockRepository)(nil).SaveDeployment), ctx, d)
}

// SaveJob mocks base method.
func (m *MockRepository) SaveJob(ctx context.Context, j model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJob", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJob indicates an expected call of SaveJob.
func (mr *MockRepositoryMockRecorder) SaveJob(ctx, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJob", reflect.TypeOf((*MockRepository)(nil).SaveJob), ctx, j)
}

// SaveRepository mocks base method.
func (m *MockRepository) SaveRepository(ctx context.Context, r model.RepositoryMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRepository", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRepository indicates an expected call of SaveRepository.
func (mr *MockRepositoryMockRecorder) SaveRepository(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRepository", reflect.TypeOf((*MockRepository)(nil).SaveRepository), ctx, r)
}

// UpdateJobStatus mocks base method.
func (m *MockRepository) UpdateJobStatus(ctx context.Context, jobID string, status model.OpStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobStatus", ctx, jobID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobStatus indicates an expected call of UpdateJobStatus.
func (mr *MockRepositoryMockRecorder) UpdateJobStatus(ctx, jobID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobStatus", reflect.TypeOf((*MockRepository)(nil).UpdateJobStatus), ctx, jobID, status)
}
